/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TodayRouteImport } from "./routes/today";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as OutputsRouteImport } from "./routes/outputs";
import { Route as ModeRouteImport } from "./routes/mode";
import { Route as InboxRouteImport } from "./routes/inbox";
import { Route as HealthRouteImport } from "./routes/health";
import { Route as DiffRouteImport } from "./routes/diff";
import { Route as IndexRouteImport } from "./routes/index";

const TodayRoute = TodayRouteImport.update({
  id: "/today",
  path: "/today",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const OutputsRoute = OutputsRouteImport.update({
  id: "/outputs",
  path: "/outputs",
  getParentRoute: () => rootRouteImport,
} as any);
const ModeRoute = ModeRouteImport.update({
  id: "/mode",
  path: "/mode",
  getParentRoute: () => rootRouteImport,
} as any);
const InboxRoute = InboxRouteImport.update({
  id: "/inbox",
  path: "/inbox",
  getParentRoute: () => rootRouteImport,
} as any);
const HealthRoute = HealthRouteImport.update({
  id: "/health",
  path: "/health",
  getParentRoute: () => rootRouteImport,
} as any);
const DiffRoute = DiffRouteImport.update({
  id: "/diff",
  path: "/diff",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/diff": typeof DiffRoute;
  "/health": typeof HealthRoute;
  "/inbox": typeof InboxRoute;
  "/mode": typeof ModeRoute;
  "/outputs": typeof OutputsRoute;
  "/privacy": typeof PrivacyRoute;
  "/today": typeof TodayRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/diff": typeof DiffRoute;
  "/health": typeof HealthRoute;
  "/inbox": typeof InboxRoute;
  "/mode": typeof ModeRoute;
  "/outputs": typeof OutputsRoute;
  "/privacy": typeof PrivacyRoute;
  "/today": typeof TodayRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/diff": typeof DiffRoute;
  "/health": typeof HealthRoute;
  "/inbox": typeof InboxRoute;
  "/mode": typeof ModeRoute;
  "/outputs": typeof OutputsRoute;
  "/privacy": typeof PrivacyRoute;
  "/today": typeof TodayRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/diff"
    | "/health"
    | "/inbox"
    | "/mode"
    | "/outputs"
    | "/privacy"
    | "/today";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/diff"
    | "/health"
    | "/inbox"
    | "/mode"
    | "/outputs"
    | "/privacy"
    | "/today";
  id:
    | "__root__"
    | "/"
    | "/diff"
    | "/health"
    | "/inbox"
    | "/mode"
    | "/outputs"
    | "/privacy"
    | "/today";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DiffRoute: typeof DiffRoute;
  HealthRoute: typeof HealthRoute;
  InboxRoute: typeof InboxRoute;
  ModeRoute: typeof ModeRoute;
  OutputsRoute: typeof OutputsRoute;
  PrivacyRoute: typeof PrivacyRoute;
  TodayRoute: typeof TodayRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/today": {
      id: "/today";
      path: "/today";
      fullPath: "/today";
      preLoaderRoute: typeof TodayRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/outputs": {
      id: "/outputs";
      path: "/outputs";
      fullPath: "/outputs";
      preLoaderRoute: typeof OutputsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mode": {
      id: "/mode";
      path: "/mode";
      fullPath: "/mode";
      preLoaderRoute: typeof ModeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/inbox": {
      id: "/inbox";
      path: "/inbox";
      fullPath: "/inbox";
      preLoaderRoute: typeof InboxRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/health": {
      id: "/health";
      path: "/health";
      fullPath: "/health";
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/diff": {
      id: "/diff";
      path: "/diff";
      fullPath: "/diff";
      preLoaderRoute: typeof DiffRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffRoute: DiffRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRoute,
  ModeRoute: ModeRoute,
  OutputsRoute: OutputsRoute,
  PrivacyRoute: PrivacyRoute,
  TodayRoute: TodayRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
